# Generated by Django 4.2.7 on 2023-11-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliers',
            name='status',
            field=models.CharField(choices=[('PD', 'PAID'), ('P', 'PENDING'), ('F', 'FAILED')], default='P', max_length=20),
        ),
    ]
