# Generated by Django 4.2.7 on 2023-11-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliers',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
    ]
