# Generated by Django 4.2.7 on 2023-11-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_appliers_email_remove_owner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliers',
            name='status',
        ),
    ]
