# Generated by Django 4.2.7 on 2023-11-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.owner')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(3, 'THREE MONTHS'), (9, 'SIX MONTHS')])),
                ('transaction_id', models.CharField(max_length=256)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='form_app.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.appliers')),
            ],
        ),
        migrations.CreateModel(
            name='FormAppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PD', 'PAID'), ('P', 'PENDING'), ('F', 'FAILED')], max_length=3)),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.appliers')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.form')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='form_app.transactionhistory')),
            ],
        ),
    ]
