# Generated by Django 4.2.7 on 2023-11-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_owner'),
        ('form_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.owner'),
        ),
    ]
