# Generated by Django 4.2.7 on 2023-11-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_remove_appliers_status'),
        ('form_app', '0003_alter_form_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.appliers')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.form')),
            ],
        ),
    ]
