# Generated by Django 4.2.7 on 2023-11-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='appliers',
        ),
    ]
