# Generated by Django 4.2.7 on 2023-11-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0006_remove_form_appliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formappliers',
            name='status',
            field=models.CharField(choices=[('PD', 'PAID'), ('P', 'PENDING'), ('F', 'FAILED')], max_length=3),
        ),
    ]
