# Generated by Django 4.2.7 on 2023-11-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0007_alter_formappliers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formappliers',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='form_app.transactionhistory'),
        ),
    ]
