# Generated by Django 4.2.7 on 2023-11-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0008_formappliers_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='form_app.form'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.IntegerField(choices=[(3, 'THREE MONTHS'), (9, 'SIX MONTHS')]),
        ),
    ]
